# Generated by Django 5.0.7 on 2024-10-30 10:22

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClayFourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClayOneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClayThreeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClayTwoReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClayFourTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('start_time', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='court_reservation.clayfourreservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('reservation', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ClayOneTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('start_time', models.CharField(choices=[('08:30', '08:30'), ('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:30', '20:30')], max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='court_reservation.clayonereservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('reservation', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ClayThreeTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('start_time', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='court_reservation.claythreereservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('reservation', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ClayTwoTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('start_time', models.CharField(choices=[('08:30', '08:30'), ('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:30', '20:30')], max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='court_reservation.claytworeservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('reservation', 'start_time')},
            },
        ),
    ]
