# Generated by Django 5.0.7 on 2024-10-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
